### ISSUE TITLE
Update to latest version of p5js needed

### ISSUE THREAD

**Issue by tegacodes** [shiffman/The-Nature-of-Code-Examples-p5.js#35]
Hey Dan, I'm going through these examples and a few of them in Chapter 2 (maybe more later but haven't got there yet) won't run as they link to an older version of p5 that doesnt support functions like the p5 vector function copy(). 

Specifically had this problem in 2.04 and 2.05 but I suppose all paths to p5 should be updated to:
http://cdn.jsdelivr.net/p5.js/latest/p5.min.js
http://cdn.jsdelivr.net/p5.js/latest/addons/p5.dom.js

**Comment by shiffman** [comment]
Ah, thanks for pointing this out.  I've gone back and forth so many times about the best way to do this.  I decided to simply link to version 0.4.22 at the moment.  I think I prefer that over "latest" in case some new features break the examples before I have a chance to update them.  I'm also linking to `p5.js` rather than `p5.min.js` for easier debugging.
